### PR TITLE
Changed MainPage loading

### PR DESCRIPTION
**Pull request by gateslm**
The commit is in the MainPage.java file. The change to the code is if statements checking if the file exists in the Github file, or if the code is in the C: directory. If not, a proper window will need to be shown if the file cannot be found compared to just having an error the program for the developers.

### CODE REVIEW

**Comment by devloop0** [comment]
Looks good, one quick question, on line 38: https://github.com/the-machine-project/the-machine/pull/27/files#diff-0531fae76c495e5506cf05571b10169fR38, why does the file also need to be executable only in C:? In fact, I don't think it needs to be executable at all; it just needs to exist and be able to be read from.
I think the error message window will be extremely helpful, can you write it or should I? If you are going to, consider looking at the javafx Alert API. Let me know what you decide. 
Once you respond to my first question, I will merge this.

**Comment by gateslm** [comment]
I don't have any experience with Javafx, and would not get the theme for the error message the same as the rest of the project. 

For the original question, I was just testing with different boolean methods that would see if it works. The execute can be removed. I can submit another pull request for that or you can. So I believe all it really needs to read it.

**Comment by gateslm** [comment]
Looking back at the code, I forgot to take that method. It works without the use of that method, when I tried when I first wrote this a week ago. If you want, I can do another pull request, as I said in the previous comment.

**Comment by devloop0** [comment]
Okay, sounds good. Just fix the canExecute() call with another commit and I'll accept your pull request.

**Pull request closed without merging**
