### PR TITLE
MainPage multi platform opencv loading

### PR DESCRIPTION
**Pull request by xnart**
It doesn't cover all platforms but should be enough to initial shift for multi platform support. 

Also i changed package name because the project's domain is "machineproject.org" so "org.machineproject.machine" is best fit for that. For more information : https://maven.apache.org/guides/mini/guide-naming-conventions.html

Edit : Looks like i messed up with project url. It should be themachineproject.org

### CODE REVIEW

**Comment by devloop0** [comment]
Quick question, here: https://github.com/xnart/the-machine/blob/master/src/main/java/org/machineproject/machine/MainPage.java#L30, if you're on Linux, it seems to be loading ./ASSETS/lib/x64/opencv_java310.so, I'm assuming that exists on your local machine. I'm assuming when packaging it, we will have to either modify the path or add the .so file at that directory, right?
Other than that, it looks pretty good, there are no merge conflicts because I'm guessing that everything is now in a different directory, but I will resolve that.

**Comment by devloop0** [comment]
Also, it would be nice to move all of this opencv dll/so loading to a separate class. Can you do this, or do you want me to?

**Comment by xnart** [comment]
Yeah you have to put the .so file in that path when you create package.

By the way, i separated loading library and put it in UserPlatform class.

**Comment by devloop0** [comment]
Okay. I'll probably modify the path later. I'll accept this merge request for now though.

**Pull request merged**
